// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;



/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAshxUWhdOXBaplsPbRKknOhjLI1hqEgfY',
    appId: '1:178924813146:web:a1f377adf51f2f96b29163',
    messagingSenderId: '178924813146',
    projectId: 'aya-recipe-app',
    authDomain: 'aya-recipe-app.firebaseapp.com',
    storageBucket: 'aya-recipe-app.firebasestorage.app',
    measurementId: 'G-7WYHEVVKZL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfaCXMt0ePDjEoSh5yZbeYMnKXXCxA4J4',
    appId: '1:178924813146:android:3aac831efaeb23b3b29163',
    messagingSenderId: '178924813146',
    projectId: 'aya-recipe-app',
    storageBucket: 'aya-recipe-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJVWdTN-VPPeKGuDRlxqELYb4qp3LvUVY',
    appId: '1:178924813146:ios:354766abb896f937b29163',
    messagingSenderId: '178924813146',
    projectId: 'aya-recipe-app',
    storageBucket: 'aya-recipe-app.firebasestorage.app',
    iosBundleId: 'com.example.recpie',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJVWdTN-VPPeKGuDRlxqELYb4qp3LvUVY',
    appId: '1:178924813146:ios:354766abb896f937b29163',
    messagingSenderId: '178924813146',
    projectId: 'aya-recipe-app',
    storageBucket: 'aya-recipe-app.firebasestorage.app',
    iosBundleId: 'com.example.recpie',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAshxUWhdOXBaplsPbRKknOhjLI1hqEgfY',
    appId: '1:178924813146:web:11af2b57a33370d4b29163',
    messagingSenderId: '178924813146',
    projectId: 'aya-recipe-app',
    authDomain: 'aya-recipe-app.firebaseapp.com',
    storageBucket: 'aya-recipe-app.firebasestorage.app',
    measurementId: 'G-R939RH8FBB',
  );
}
